### ISSUE TITLE
Pokemon can be withdrawn by clicking a party member.

### ISSUE THREAD

**Issue by Lord-Haji** [HoeenCoder/SpacialGaze#110]
![scrnsht](https://i.gyazo.com/a7bad6402e5377401bec8bb99983c7ea.gif)

**Comment by HoeenCoder** [comment]
I dont see the bug

**Comment by HoeenCoder** [comment]
Youll need to detail whats happening here, you shouldnt be able to click a disabled button, im assuming thats whats happening when vivillion is moving in the PC box.
