### ISSUE TITLE
Addition of Metronome Battles

### ISSUE THREAD

**Issue by Lord-Haji** [HoeenCoder/SpacialGaze#19]
![scrnsht](http://i.imgur.com/BsHNVnZ.png)

Tracking: ✓

1. [x] Ban Ubers and Mega Rayquaza 
2. [ ] Ban Healing items and abilities
3. [x] Remove Immunity i.e convert all immunity to not very effective
4. [ ] Only Allowed Move is Metronome

**Comment by HoeenCoder** [comment]
You don't really need to create an issue for this. Issues should be used for well issues on existing code. If your having problems with adding something the development room is there for that purpose. Just link us to your branch that has the code, and tell us about the issue.
