### ISSUE TITLE
Suggestions and Bugs

### ISSUE THREAD

**Issue by HoeenCoder** [HoeenCoder/SpacialGaze#2]
## Master list of known bugs and suggestions for SpacialGaze

I will be keeping this updated as time goes by, refer to here if you want an idea of what you can do for us.
Also, be sure to visit us on http://spacialgaze.psim.us/development and discuss your changes with us. We don't want to turn down that pull request you worked so hard on!
### Known Bugs

 - [x] Uno join messages show twice. http://i.imgur.com/KE6F76s.jpg

 - [x] Daily stardust frozen at 1 per day

 - [ ] (node:1524) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Found a bug?** Report it to us in our [development room](http://spacialgaze.psim.us/development).
### Suggestions List
- [x] Setup a command that lists all the custom moves for each SGSSB pokemon.

- [x] Setup a command that lists all the custom moves avaliable for anyone to use in SSBFFA.

- [x] Setup a command that lists all the custom moves for each pokemon in Retro Super Staff Bros.

- [x] Add descriptions to the moves and abilities in Digimon Showdown.

- [x] Add descriptions to the moves in PMD.

- [ ] Allow multiple, collapsible polls in rooms.

- [ ] Allow multiple, collapsible surveys in rooms.

- The SG Game Project has TONS todo. [Project link](https://github.com/HoeenCoder/SpacialGaze/projects/2)

**Have a suggestions?** Tell us about it, were always open to new ideas! Contact a staff member on the [server](http://spacialgaze.psim.us), or use the [development room](http://spacialgaze.psim.us/development)

**Comment by Volco** [comment]
HoeenHero when you get a chance pm me on SpacialGaze i figured out the emoticon issue (i'd commit it but you said dont for a few days so letting you do the preps but ill tell you how to fix it in pms i also sent a tell)

**Comment by HoeenCoder** [comment]
@Volcos feel free to PR to master branch

Also i don't recall telling anyone not to commit / PR anything.

**Comment by Volco** [comment]
oh alright i thought you did lel ok ill commit it

**Comment by Lord-Haji** [comment]
@Volcos you being immaginative these days lel :)

**Comment by Lord-Haji** [comment]
If

**Comment by Lord-Haji** [comment]
Checkout News system updates at #50

**Comment by Lord-Haji** [comment]
Moment deprecated at #51

**Comment by Lord-Haji** [comment]
@HoeenCoder /tierpoll isn't spammy now.

**Comment by ghost** [comment]
The question is, whil digimon Showdown be added to master or not?

**Comment by HoeenCoder** [comment]
It will, it was added to afd for testing on 4/1

**Comment by ghost** [comment]
new issue: when you change alts while you join a tournament, you cannot join and the username in the tour  changes to guest

**Comment by HoeenCoder** [comment]
Thats something to be fixed on main

**Comment by ghost** [comment]
Oh ok

**Comment by ghost** [comment]
Just a minor suggestion, maybe add a doc that includes all the staffmons and their data on them like super staffbros melee. we can use the gist function on github for that.

**Comment by ghost** [comment]
Retro ssb exists as well, make one for that

**Comment by ghost** [comment]
Uno join message [appears twice](http://i.imgur.com/KE6F76s.jpg) (its stella btw. I changed my name to Eelek).

**Comment by ghost** [comment]
Uno message loses formatting and shows code: http://i.imgur.com/iJmmnEv.jpg

:/

Eeledit: #214 fixes issue

**Comment by ghost** [comment]
Daily bonus seems to be frozen at 1 stardust every day

**Comment by HoeenCoder** [comment]
Too busy to fix that atm, added to list

**Comment by DeathlyPlays** [comment]
I'll do the SSB Entries @HoeenCoder

**Comment by DeathlyPlays** [comment]
But when I do them I want to do a full out data thing like how Exiled has (analyses and ranks)

**Comment by DeathlyPlays** [comment]
I'll add ranks when I am more knowledgeable of the meta.

**Comment by HoeenCoder** [comment]
This deprecation should be handled soon, dosen't seem to be too difficult so ill post it here.

`(node:1524) DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

**Comment by DeathlyPlays** [comment]
Well all we have left is the RSSB data, we've done descriptions for the others

**Comment by ghost** [comment]
Something discussed was improving surveys and polls to have multiple polls/surveys (as well as make them collapsible) and include text formatting in survey answers (like <s>ludicolo</s> instead of ~~ ludicolo ~~)

**Comment by HoeenCoder** [comment]
Updated

**Comment by ghost** [comment]
Other thingy, People can over set them so make some sort of message when something is set (I may do it but what ever)

**Comment by HoeenCoder** [comment]
over set them?

**Comment by ghost** [comment]
Sorry for the dumb sentence. sometimes more than one person can set a custom color or avatar accidentally because there's no notification that someone did it besides the modlog.

Example: Yesterday C7 Set Pra's Color even though KM set it first.

**Comment by Mystifi** [comment]
That's a quick fix with the shop commands, though.

**Comment by ghost** [comment]
Our random metagames (spefically the ssb series and digimon showdown) need to be modified to use random-teams.js instead of putting everything in scripts.js

**Comment by DeathlyPlays** [comment]
@Gligar I figured that's what the issue was

**Comment by DeathlyPlays** [comment]
Uploading the RSSB data for move update @HoeenCoder (I already marked it off the list https://github.com/HoeenCoder/SpacialGaze/commit/73dc21c2692fc2d969ed1dfb0e0b574886eb673b)

**Comment by ghost** [comment]
Daily Bonus stopped working altogether

No Bonus when logging in, When doing /bonus it displays "Your next bonus is 1 Stardust in 1 day"

**Comment by HoeenCoder** [comment]
I indetified this issue last night, its not applying to new names because of an early `return` statement, ill tweak it a bit so it works.

**Comment by DeathlyPlays** [comment]
@HoeenCoder you can mark off adding descriptions to Digimon Showdown moves & abilities btw

**Comment by ghost** [comment]
Resetting stardust seems to fail

**Comment by Mystifi** [comment]
I will hopefully open a PR tomorrow with fixes to the DeprecationWarning; it's actually simple, but the reason I will PR is because I would like @HoeenCoder's help in catching any extraneous instances that I happen to miss.
