### ISSUE TITLE
[SGgame] COM sometimes fails to move.

### ISSUE THREAD

**Issue by HoeenCoder** [HoeenCoder/SpacialGaze#212]
When in battle with the COM (SG Server) sometimes, it will fail to make a move. I haven't identified any pattern to this occurence yet, all I know is information is getting received by the battle process because ``/evalbattle SG.decideCOM(this, "p1", "random");`` fails to force a decision.

Some help fixing this would be appreciated.

EDIT: A possible pattern i've just noticed is the COM _often but not always_ freezes after you make a switch.

**Comment by HoeenCoder** [comment]
It is believed this is occurring if CPU usage hits the roof (99%, 100%)

**Comment by DeathlyPlays** [comment]
Indeed @HoeenCoder
