### ISSUE TITLE
Did i just get banned ?

### ISSUE THREAD

**Issue by Lord-Haji** [HoeenCoder/SpacialGaze#259]
@HoeenCoder

**Comment by HoeenCoder** [comment]
Goodbye

**Comment by DeathlyPlays** [comment]
Goodbye farewell I won't sayeth no more.... Wait I will you were permaed from SG for overall toxicity

**Comment by Mystifi** [comment]
I literally have wanted you gone for so long. You've done nothing but pester me about the work I've done, take code from a lot of sources and take credit for it after making 50+ commits that broke each other just so you can get more. You just got on my last nerve from the very beginning. I will not miss you, and quite frankly, I'm so happy you're gone.
Please learn to code well. Stealing code and slightly modifying it isn't coding, it's basically plagiarism. You can't consider yourself a coder when the biggest thing you do is break your own stuff to get more commits. Goodbye, please stop pestering servers until you can learn to be a better presence, a better coder, and just a better person overall

EDIT: Not to mention the fact that you were really creepy at points to specific staff...that's absolutely not okay, either. Quit pestering female staff for their Facebook pages to friend them.
