### ISSUE TITLE
Polls become spammy sometimes

### ISSUE THREAD

**Issue by Lord-Haji** [HoeenCoder/SpacialGaze#94]
Kinda Like:
![scrnsht](https://i.gyazo.com/611d76d94b8499cc7582ea79ba2da4d4.gif)
**Specially tpoll**

Ok if u cant see the screenshot go <a href="https://i.gyazo.com/611d76d94b8499cc7582ea79ba2da4d4.gif">Here!</a>

**Comment by Lord-Haji** [comment]
<img src="https://i.gyazo.com/611d76d94b8499cc7582ea79ba2da4d4.gif">

**Comment by Lord-Haji** [comment]
@HoeenCoder I think displaying polls side ways will be great!
and for results options with 0 votes will not be shown

**Comment by Lord-Haji** [comment]
I dont think we need to care much bout main coz tpoll isnt legit in main

**Comment by HoeenCoder** [comment]
Regular polls can stay the way they are, if you want to make a seperate set of rules for tier polls thats fine.

Possibly something like:

```javascript
class Tierpoll extends Poll {
  super(room, questionData, options);
  // Modify functions to not be so spammy with alot of vote options
}
```
